### PR TITLE
Feature/wim 1274

### PR DESCRIPTION
**Pull request by robertragas**
Feature:

Mime mail now allows to send attachments

HTT

1. Make a webform and choose to send attachments with email.
2. Make a filefield
3. Use the form and check mailcatcher, you see that the file is attached now.
 
P.S try it with private/public and delete submission on delete right away / 1 day.

### CODE REVIEW

**Comment by kedramon** [comment]
@robertragas Fatal error: Call to undefined function mailsystem_set() in /var/www/html/sites/all/modules/contrib/mimemail/mimemail.install on line 13

**Comment by ozin7** [comment]
@robertragas you need to add MailSystem module. Why do you need the field_send_attachments_with_emai field?
@kedramon is it ok to have field_reminder_email field in features?

**Comment by robertragas** [comment]
@kedramon @ozin7 The field reminder needs to be removed yes,
The reason why field_send_attachments_with_emai is so people can choose to send attachments with email because its optional.

**Comment by kedramon** [comment]
@robertragas @ozin7 field field_reminder_email should be deleted.

**Pull request merged**
