### PR TITLE
WIM-1331 - set default linkit profile to aliased paths in update hook

### PR DESCRIPTION
**Pull request by robertragas**
Created an update hook for aliased paths. Couldn't find one and also saw it working in the installation profile itself.

### CODE REVIEW

**Comment by ozin7** [comment]
@kedramon is profiles for linkit in features or not?

**Comment by kedramon** [comment]
@ozin7, @robertragas  linkit profile is in wim_text_formats feature, we should update it to prevent overrides.

**Comment by robertragas** [comment]
Oki I will check the features

**Comment by robertragas** [comment]
I see it is already set correctly. While testing I think the feature was not reverted. 
So closing this branch.

**Pull request closed without merging**
